#!/bin/sh
# =====================================================================
# run-tests.sh — the pre-flight gate for this config
# =====================================================================
# Runs everything that can be checked WITHOUT a Mac, without Hammerspoon,
# and without touching the running config. One command, one exit code.
#
#     hammerspoon/tools/run-tests.sh            # from anywhere in the repo
#     hammerspoon/tools/run-tests.sh /path/to/hammerspoon
#
# WHY THIS EXISTS. The bugs that reached me in 6.44.x were not subtle —
# an Attach button that wiped the draft, a Send button that answered
# "nothing queued" with the note visible on screen. They survived because
# the suites only ever read the page's JavaScript as TEXT. Grepping source
# for a function name proves the name is present; it proves nothing about
# what happens when you click. Stage 3 below closes that: it executes the
# real page script against a DOM stub and drives the real onclick strings.
#
# WHAT EACH STAGE ACTUALLY COVERS — worth being blunt about, because a
# green run is only worth what it checked:
#
#   1. SYNTAX     luac -p on init.lua, core/ and every module. Catches the
#                 class of mistake that leaves Hammerspoon dead on launch.
#                 core/ holds the three big blocks lifted out of init.lua in
#                 6.44.11 — they are dofile'd at a fixed point rather than
#                 loaded by the module loader, so a broken one is NOT
#                 isolated the way a broken module is.
#   2. LUA        the forty-one suites, run against the REAL module files.
#   3. PAGE JS    the Capture Pad's page, generated by the real module and
#                 then EXECUTED. Needs node; skipped loudly without it.
#
# WHAT IT DOES NOT COVER, and no amount of green here will: anything that
# needs a real WKWebView, real screens, real permissions, or a real Asana.
# For the state of an actual install, use hs-doctor.sh instead.
#
# Both tools are read-only. Neither writes into ~/.hammerspoon.
# =====================================================================

HS="${1:-}"
if [ -z "$HS" ]; then
    # the directory this script lives in, minus /tools
    d=$(dirname "$0")
    HS=$(cd "$d/.." 2>/dev/null && pwd)
fi

if [ ! -f "$HS/init.lua" ]; then
    echo "✗ no init.lua under: $HS"
    echo "  pass the hammerspoon directory explicitly:"
    echo "      $0 /path/to/hammerspoon"
    exit 2
fi

# A scratch directory for generated files, cleaned up on every exit path
# including Ctrl-C — nothing this script makes should outlive it.
WORK=$(mktemp -d 2>/dev/null || mktemp -d -t hstests)
trap 'rm -rf "$WORK"' EXIT HUP INT TERM

# Find a Lua. Hammerspoon embeds its own and does not expose a CLI, so this
# is a separate install: `brew install lua` on a Mac you administer. On the
# work Mac, where there is no admin right, expect this to be missing — that
# is what hs-doctor.sh is for.
LUA=""
for c in lua5.4 lua54 lua5.3 lua; do
    if command -v "$c" >/dev/null 2>&1; then LUA="$c"; break; fi
done

NODE=""
for c in node /opt/node22/bin/node; do
    if command -v "$c" >/dev/null 2>&1; then NODE="$c"; break; fi
done

STAGES_RUN=0
FAILED=0
SKIPPED=""

echo "── Hammerspoon config: pre-flight ──"
echo "   dir : $HS"
VER=$(grep -m1 -o 'ARCHITECTURE VERSION CONTROL: [^ ]*' "$HS/init.lua" 2>/dev/null | cut -d' ' -f4)
echo "   ver : ${VER:-unknown}"
echo "   lua : ${LUA:-not found}"
echo "   node: ${NODE:-not found}"
echo ""

# ---------------------------------------------------------------- 1. syntax
echo "1. SYNTAX"
if [ -z "$LUA" ]; then
    echo "   ⚠️  skipped — no lua interpreter on PATH"
    SKIPPED="$SKIPPED syntax"
else
    STAGES_RUN=$((STAGES_RUN + 1))
    # luac is not always installed next to lua; loadfile is equivalent for a
    # syntax check and always available.
    #
    # THE PATH GOES THROUGH THE ENVIRONMENT, NOT THE ARGUMENT LIST. `lua -e
    # 'chunk' file.lua` does not hand file.lua to the chunk — it runs the
    # chunk and then EXECUTES file.lua. The first version of this loop did
    # that and booted the whole config: 26 "Architecture Fault" lines and a
    # nil `hs`, reported as a syntax error in a file that is perfectly valid.
    syn_fail=0
    for f in "$HS/init.lua" "$HS"/core/*.lua "$HS"/modules/*.lua; do
        [ -f "$f" ] || continue
        if command -v luac5.4 >/dev/null 2>&1; then
            msg=$(luac5.4 -p "$f" 2>&1)
        elif command -v luac >/dev/null 2>&1; then
            msg=$(luac -p "$f" 2>&1)
        else
            msg=$(HS_SYNTAX_FILE="$f" "$LUA" -e \
                'local ok, err = loadfile(os.getenv("HS_SYNTAX_FILE")); if not ok then io.write(err) end' 2>&1)
        fi
        if [ -n "$msg" ]; then
            echo "   ✗ $(basename "$f"): $msg"
            syn_fail=$((syn_fail + 1))
        fi
    done
    # The shell tools ship too, and a broken one is discovered at the
    # worst possible moment — hs-install.sh runs when the config is
    # half-copied. `sh -n` parses without executing.
    for t in "$HS"/tools/*.sh; do
        [ -f "$t" ] || continue
        msg=$(sh -n "$t" 2>&1) || {
            echo "   ✗ $(basename "$t"): $msg"
            syn_fail=$((syn_fail + 1))
        }
    done
    n=$(ls "$HS"/modules/*.lua 2>/dev/null | wc -l | tr -d ' ')
    nc=$(ls "$HS"/core/*.lua 2>/dev/null | wc -l | tr -d ' ')
    if [ "$syn_fail" -eq 0 ]; then
        echo "   ✅ init.lua + $nc core + $n modules compile · $(ls -1 "$HS"/tools/*.sh 2>/dev/null | wc -l | tr -d ' ') shell tools parse"
    else
        echo "   ❌ $syn_fail file(s) will not compile — Hammerspoon would not start"
        FAILED=$((FAILED + 1))
    fi
fi
echo ""

# ------------------------------------------------------------- 1b. lint
# Runs BEFORE the suites on purpose. Every rule in hs-lint is a bug that
# actually reached LL's Mac, and most of them are the kind that a unit
# test cannot see: an Accessibility call with no timeout is correct Lua
# that passes every test and freezes a real keyboard. Static first, then
# behaviour.
echo "1b. LINT (the bugs this config has actually shipped)"
if [ -f "$HS/tools/hs-lint.lua" ]; then
    if "$LUA" "$HS/tools/hs-lint.lua" "$HS"; then
        echo "   ✅ no ERROR-level findings"
    else
        echo "   ❌ hs-lint found ERROR-level problems — see above"
        FAILED=$((FAILED + 1))
    fi
else
    echo "   ⚠️  tools/hs-lint.lua missing — static checks skipped"
fi
echo ""

# --------------------------------------------------------- 1c. hostile world
# Every suite in tests/ stubs `hs` to behave WELL. This runs all 46
# modules against a Mac that answers nil to everything — no screens, an
# empty pasteboard, no Accessibility, a folder that is not there. Those
# are real shapes, not hypotheticals, and a module that throws on them
# throws on somebody's Monday morning.
echo "1c. HOSTILE WORLD (every API answers nil)"
if [ -n "$LUA" ] && [ -f "$HS/tools/hs-hostile.lua" ]; then
    STAGES_RUN=$((STAGES_RUN + 1))
    if out=$("$LUA" "$HS/tools/hs-hostile.lua" "$HS" empty 2>&1); then
        echo "   ✅ $(echo "$out" | head -1 | sed 's/^── //')"
    else
        echo "   ❌ a module did not degrade:"
        echo "$out" | tail -n +2 | head -8 | sed 's/^/     /'
        FAILED=$((FAILED + 1))
    fi
else
    echo "   ⚠️  skipped"
fi
echo ""

# ------------------------------------------------------------------- 2. lua
echo "2. LUA SUITES"
if [ -z "$LUA" ]; then
    echo "   ⚠️  skipped — no lua interpreter on PATH"
    SKIPPED="$SKIPPED lua-suites"
else
    for t in test_features test_daily_backup test_window_return test_win_pin test_rollup test_switcher test_modules test_cheatsheet test_diagnostics test_mouse_grid test_url_cleaner test_health test_menubar test_app_launcher test_chrome_history test_begone test_recent_docs test_focus test_rename test_notices test_console test_search_index test_doc_keywords test_clipboard test_select_mode test_ocr_tag test_file_tracker test_app_watcher test_integration test_tools test_expander test_autocorrect test_keycaster test_keyboard_stack test_hyper_key test_screenshots test_taskform test_task_creator test_note_pad test_editor test_editor_picker test_right_click test_write_ledger test_window_move test_unified test_style test_menu_search test_settings_panes test_app_kill test_power_tools test_tab_search test_net_tools test_mac_panel test_arranger test_activity_url test_lag test_text_case test_define test_dialog_home test_battery_saver; do
        f="$HS/tests/$t.lua"
        if [ ! -f "$f" ]; then
            echo "   ⚠️  $t — missing"
            continue
        fi
        STAGES_RUN=$((STAGES_RUN + 1))
        out=$("$LUA" "$f" "$HS" 2>&1)
        line=$(echo "$out" | grep -E '[0-9]+ passed, [0-9]+ failed' | tail -1)
        if [ -z "$line" ]; then
            echo "   ❌ $t — did not finish:"
            echo "$out" | tail -5 | sed 's/^/        /'
            FAILED=$((FAILED + 1))
        elif echo "$line" | grep -q ', 0 failed'; then
            echo "   ✅ $t — $line"
        else
            echo "   ❌ $t — $line"
            echo "$out" | grep -E '^\s*(❌|FAIL)' | head -10 | sed 's/^/        /'
            FAILED=$((FAILED + 1))
        fi
    done
fi
echo ""

# --------------------------------------------------------------- 3. page JS
echo "3. CAPTURE PAD — PAGE JAVASCRIPT, EXECUTED"
if [ -z "$LUA" ] || [ -z "$NODE" ]; then
    echo "   ⚠️  skipped — needs both lua and node"
    echo "      This is the stage that catches the click-path bugs. If it is"
    echo "      skipped, the Capture Pad's buttons are UNTESTED this run."
    SKIPPED="$SKIPPED page-js"
elif [ ! -f "$HS/tests/dump_pad_html.lua" ] || [ ! -f "$HS/tests/test_pad_js.js" ]; then
    echo "   ⚠️  skipped — harness files missing from tests/"
    SKIPPED="$SKIPPED page-js"
else
    STAGES_RUN=$((STAGES_RUN + 1))
    # The page is GENERATED by the shipped module, never hand-written here,
    # so the harness can only ever be testing what actually ships.
    if "$LUA" "$HS/tests/dump_pad_html.lua" "$HS/modules" > "$WORK/pad.html" 2>"$WORK/pad.err"; then
        out=$("$NODE" "$HS/tests/test_pad_js.js" "$WORK/pad.html" 2>&1)
        line=$(echo "$out" | grep -E '[0-9]+ passed, [0-9]+ failed' | tail -1)
        if echo "$line" | grep -q ', 0 failed'; then
            echo "   ✅ test_pad_js — $line"
        else
            echo "   ❌ test_pad_js — ${line:-did not finish}"
            echo "$out" | grep -E '^\s*(❌|FAIL)' | head -10 | sed 's/^/        /'
            FAILED=$((FAILED + 1))
        fi
    else
        echo "   ❌ the pad's HTML could not be generated:"
        tail -5 "$WORK/pad.err" | sed 's/^/        /'
        FAILED=$((FAILED + 1))
    fi
fi
echo ""

# ------------------------------------------- 3b. blur editor page JS
echo "3b. SCREENSHOT EDITOR — PAGE JAVASCRIPT, EXECUTED"
if [ -z "$LUA" ] || [ -z "$NODE" ]; then
    echo "   ⚠️  skipped — needs both lua and node"
    echo "      The blur itself lives in this page. If this is skipped,"
    echo "      the editor's core is UNTESTED this run."
    SKIPPED="$SKIPPED editor-js"
elif [ ! -f "$HS/tests/dump_editor_html.lua" ] || [ ! -f "$HS/tests/test_editor_js.js" ]; then
    echo "   ⚠️  skipped — harness files missing from tests/"
    SKIPPED="$SKIPPED editor-js"
else
    STAGES_RUN=$((STAGES_RUN + 1))
    if "$LUA" "$HS/tests/dump_editor_html.lua" "$HS/modules" > "$WORK/editor.html" 2>"$WORK/editor.err"; then
        out=$("$NODE" "$HS/tests/test_editor_js.js" "$WORK/editor.html" 2>&1)
        line=$(echo "$out" | grep -E '[0-9]+ passed, [0-9]+ failed' | tail -1)
        if echo "$line" | grep -q ', 0 failed'; then
            echo "   ✅ test_editor_js — $line"
        else
            echo "   ❌ test_editor_js — ${line:-did not finish}"
            echo "$out" | grep -E '^\s*(❌|FAIL)' | head -10 | sed 's/^/        /'
            FAILED=$((FAILED + 1))
        fi
    else
        echo "   ❌ the editor's HTML could not be generated:"
        tail -5 "$WORK/editor.err" | sed 's/^/        /'
        FAILED=$((FAILED + 1))
    fi
fi
echo ""

# ------------------------------------------- 3c. unified search page JS
echo "3c. UNIFIED SEARCH — PAGE JAVASCRIPT, EXECUTED"
if [ -z "$LUA" ] || [ -z "$NODE" ]; then
    echo "   ⚠️  skipped — needs both lua and node"
    echo "      The filter, @tags and keyboard live in this page. If this is"
    echo "      skipped, ⇪space's behaviour is UNTESTED this run."
    SKIPPED="$SKIPPED unified-js"
elif [ ! -f "$HS/tests/dump_unified_html.lua" ] || [ ! -f "$HS/tests/test_unified_js.js" ]; then
    echo "   ⚠️  skipped — harness files missing from tests/"
    SKIPPED="$SKIPPED unified-js"
else
    STAGES_RUN=$((STAGES_RUN + 1))
    if "$LUA" "$HS/tests/dump_unified_html.lua" "$HS/modules" > "$WORK/unified.html" 2>"$WORK/unified.err"; then
        out=$("$NODE" "$HS/tests/test_unified_js.js" "$WORK/unified.html" 2>&1)
        line=$(echo "$out" | grep -E '[0-9]+ passed, [0-9]+ failed' | tail -1)
        if echo "$line" | grep -q ', 0 failed'; then
            echo "   ✅ test_unified_js — $line"
        else
            echo "   ❌ test_unified_js — ${line:-did not finish}"
            echo "$out" | grep -E '^\s*(❌|FAIL)' | head -10 | sed 's/^/        /'
            FAILED=$((FAILED + 1))
        fi
    else
        echo "   ❌ the search page's HTML could not be generated:"
        tail -5 "$WORK/unified.err" | sed 's/^/        /'
        FAILED=$((FAILED + 1))
    fi
fi
echo ""

# ---------------------------------------------------------------- the verdict
echo "──"
if [ -n "$SKIPPED" ]; then
    echo "skipped:$SKIPPED"
fi
if [ "$STAGES_RUN" -eq 0 ]; then
    echo "⚠️  NOTHING RAN. This is not a pass."
    exit 2
elif [ "$FAILED" -eq 0 ]; then
    echo "✅ $STAGES_RUN stage(s) green."
    [ -n "$SKIPPED" ] && echo "   Green for what ran — see the skips above."
    exit 0
else
    echo "❌ $FAILED stage(s) failed. Do not ship this."
    exit 1
fi
